# Generated by Django 2.1.2 on 2019-08-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0096_auto_20190810_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuecamp',
            name='taluk',
            field=models.CharField(choices=[('adoor', 'Adoor'), ('alathoor', 'Alathoor'), ('aluva', 'Aluva'), ('ambalappuzha', 'Ambalappuzha'), ('chalakudy', 'Chalakudy'), ('changanasserry', 'Changanasserry'), ('chavakkad', 'Chavakkad'), ('chenganoor', 'Chenganoor'), ('cherthala', 'Cherthala'), ('chirayinkeezhu', 'Chirayinkeezhu'), ('chittur', 'Chittur'), ('devikulam', 'Devikulam'), ('eranad', 'Eranad'), ('hosdurg', 'Hosdurg'), ('idukki', 'Idukki'), ('iritty', 'Iritty'), ('kanayannur', 'Kanayannur'), ('kanjirappally', 'Kanjirappally'), ('kannur', 'Kannur'), ('karthikappally', 'Karthikappally'), ('karunagappally', 'Karunagappally'), ('kasaragod', 'Kasaragod'), ('kattakkada', 'Kattakkada'), ('kochi', 'Kochi'), ('kodungallur', 'Kodungallur'), ('kollam', 'Kollam'), ('kondotty', 'Kondotty'), ('konni', 'Konni'), ('kothamangalam', 'Kothamangalam'), ('kottarakkara', 'Kottarakkara'), ('kottayam', 'Kottayam'), ('koyilandy', 'Koyilandy'), ('kozhencherry', 'Kozhencherry'), ('kozhikode', 'Kozhikode'), ('kunnamkulam', 'Kunnamkulam'), ('kunnathoor', 'Kunnathoor'), ('kunnathunad', 'Kunnathunad'), ('kuttanad', 'Kuttanad'), ('mallappally', 'Mallappally'), ('mananthavady', 'Mananthavady'), ('manjeswaram(uppala)', 'Manjeswaram(Uppala)'), ('mannarkkad', 'Mannarkkad'), ('mavelikkara', 'Mavelikkara'), ('meenachil', 'Meenachil'), ('mukundapuram', 'Mukundapuram'), ('muvattupuzha', 'Muvattupuzha'), ('nedumangadu', 'Nedumangadu'), ('neyyattinkara', 'Neyyattinkara'), ('nilambur', 'Nilambur'), ('north paravur', 'North Paravur'), ('ottappalam', 'Ottappalam'), ('palakkad', 'Palakkad'), ('pathanapuram', 'Pathanapuram'), ('pattambi', 'Pattambi'), ('payyannur', 'Payyannur'), ('peermade', 'Peermade'), ('perinthalmanna', 'Perinthalmanna'), ('ponnani', 'Ponnani'), ('punalur', 'Punalur'), ('ranni', 'Ranni'), ('sulthan bathery', 'Sulthan Bathery'), ('taliparamba', 'Taliparamba'), ('thalapilly', 'Thalapilly'), ('thalassery', 'Thalassery'), ('thamarassery', 'Thamarassery'), ('thiroorangadi', 'Thiroorangadi'), ('thiruvalla', 'Thiruvalla'), ('thiruvananthapuram', 'Thiruvananthapuram'), ('thodupuzha', 'Thodupuzha'), ('thrissur', 'Thrissur'), ('tirur', 'Tirur'), ('udumbanchola', 'Udumbanchola'), ('vaikom', 'Vaikom'), ('varkala', 'Varkala'), ('vatakara', 'Vatakara'), ('vellarikundu', 'Vellarikundu'), ('vythiri', 'Vythiri')], max_length=50, verbose_name='Taluk - താലൂക്ക്'),
        ),
    ]
