# Generated by Django 2.1.2 on 2019-08-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0097_auto_20190810_0339'),
        ('mainapp', '0096_auto_20190810_1159'),
    ]

    operations = [
    ]
