# Generated by Django 2.1.2 on 2019-08-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0098_merge_20190810_2013'),
        ('mainapp', '0097_auto_20190810_1757'),
    ]

    operations = [
    ]
