# Generated by Django 2.1.2 on 2019-08-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0099_merge_20190811_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuecamp',
            name='taluk',
            field=models.CharField(max_length=50, verbose_name='Taluk - താലൂക്ക്'),
        ),
    ]
