# Generated by Django 2.2.4 on 2019-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0101_auto_20190811_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
